"""feat: add initial models

Revision ID: 78b3dacb9b10
Revises: 
Create Date: 2025-12-24 23:14:40.344208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b3dacb9b10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('tds_ppm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_ts'), ['ts'], unique=False)

    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('tds_ppm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_ts'), ['ts'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pw_hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=32), nullable=True),
    sa.Column('temp_warn', sa.Float(), nullable=True),
    sa.Column('temp_danger', sa.Float(), nullable=True),
    sa.Column('tds_warn', sa.Integer(), nullable=True),
    sa.Column('tds_danger', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_device_id'), ['device_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_device_id'))

    op.drop_table('device')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_ts'))
        batch_op.drop_index(batch_op.f('ix_telemetry_device_id'))

    op.drop_table('telemetry')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_ts'))
        batch_op.drop_index(batch_op.f('ix_alert_device_id'))

    op.drop_table('alert')
    # ### end Alembic commands ###
